FROM benoitj/docker-emacs:latest

LABEL maintainer="Benoit Joly <benoit@benoitj.ca>"

RUN pacman -S --noconfirm \
    ditaa \
    graphviz \
    jdk11-openjdk \
    plantuml \
    plantuml-ascii-math \
    stow

ENV USERNAME="benoit"

COPY init.d /init.d

WORKDIR /home/benoit
VOLUME /home/benoit
